cache:
  apt: true
  directories:
    - $HOME/.cache/pip
language: python
notifications:
  email: false
python:
  - 3.6
  - 3.7
sudo: false
before_install:

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest
  - conda env update -n test-environment --file environment.yml
  - conda activate test-environment
  - python3 setup.py install
script:
  - python3 -m pytest
