name: see_3_6
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - numpy=1.19.*
  - fire
  - imageio
  - pathlib
  - attrdict
  - tqdm
  - pandas
  - matplotlib
  - notebook
  - jupyter_contrib_nbextensions
  - opencv=4.4.*
  - scikit-image=0.17.*

