name: see_3_6
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - fire
  - imageio
  - pathlib
  - attrdict
  - tqdm
  - pandas
  - matplotlib
  - notebook
  - jupyter_contrib_nbextensions
  - scikit-image

